### ISSUE TITLE
Error: Module 'dotenv' Not Found During Script Execution

### ISSUE THREAD

**Issue by hassanAdamineJad** [MRezaSafari/Picsart-Interview-Task#1]
When executing the npm run start, an error occurs stating that the module 'dotenv' cannot be found.

![Screenshot 2024-07-17 at 13 25 47](https://github.com/user-attachments/assets/f7d8f88d-a11d-4e62-a9e4-4df31dc937fb)

**Comment by MRezaSafari** [comment]
npm i dotenv 
بزنید حل میشه :))

**Comment by hassanAdamineJad** [comment]
درسته :))
فقط خواستم بگم اطلاع داشته باشین و دوست داشتین آپدیت کنین همین

**Comment by MRezaSafari** [comment]
ممنونم ازت
